package com.acme.insurance.pas.rating;

import org.junit.Test;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * Characterization test: runs the PREMBAT parity fixtures through
 * {@link PremiumCalculator} and compares every field against the output of
 * the COBOL program compiled with GnuCOBOL (expected/cobol-golden.psv,
 * regenerated by modernization/prembat/run-parity.sh --update-golden).
 */
public class PrembatParityTest {

    private static final Path PARITY_DIR = Paths.get("..", "modernization", "prembat");
    private static final Path JAVA_OUT = Paths.get("target", "parity", "java-out.psv");

    private final PremiumCalculator calculator = new PremiumCalculator();

    @Test
    public void javaMatchesCobolForEveryFixture() throws IOException {
        List<String> inputs = new ArrayList<String>();
        inputs.addAll(readLines(PARITY_DIR.resolve("fixtures/legacy-cases.dat")));
        inputs.addAll(readLines(PARITY_DIR.resolve("fixtures/factor-sweep.dat")));
        List<String> golden = readLines(PARITY_DIR.resolve("expected/cobol-golden.psv"));

        List<String> javaOut = new ArrayList<String>();
        int legacy = 0;
        int sweep = 0;
        int halfUpDivergences = 0;
        for (String line : inputs) {
            if (line.isEmpty() || line.charAt(0) == '*') {
                continue;
            }
            char mode = line.charAt(0);
            String caseId = line.substring(1, 13).trim();
            String policyType = line.substring(13, 16);
            RatingFactors factors;
            if (mode == 'L') {
                factors = RatingFactors.LEGACY;
                legacy++;
            } else {
                factors = new RatingFactors(factor(line, 16), factor(line, 23), factor(line, 30));
                sweep++;
            }
            PremiumBreakdown b = calculator.calculate(policyType, factors);
            if (halfUpFinalPremium(policyType, factors).compareTo(b.getFinalPremium()) != 0) {
                halfUpDivergences++;
            }
            javaOut.add(mode + "|" + caseId + "|[" + policyType + "]|"
                    + money(b.getBasePremium()) + "|" + money(b.getTerritoryPremium()) + "|"
                    + money(b.getClassPremium()) + "|" + money(b.getModifiedPremium()) + "|"
                    + money(b.getTaxAmount()) + "|" + money(b.getSurcharge()) + "|"
                    + money(b.getFinalPremium()));
        }

        Files.createDirectories(JAVA_OUT.getParent());
        Files.write(JAVA_OUT, javaOut, StandardCharsets.UTF_8);

        int mismatches = 0;
        assertEquals("case count", golden.size(), javaOut.size());
        for (int i = 0; i < golden.size(); i++) {
            if (!golden.get(i).equals(javaOut.get(i))) {
                mismatches++;
                System.out.println("PARITY MISMATCH cobol=" + golden.get(i)
                        + " java=" + javaOut.get(i));
            }
        }

        System.out.println("PARITY | legacy cases (verbatim 3200 paragraph) | " + legacy);
        System.out.println("PARITY | factor-sweep cases (parameterised)      | " + sweep);
        System.out.println("PARITY | fields compared per case                | 7");
        System.out.println("PARITY | mismatches                              | " + mismatches);
        System.out.println("PARITY | cases a HALF_UP port would get wrong     | " + halfUpDivergences);
        assertEquals("COBOL/Java mismatches", 0, mismatches);
        assertTrue("sweep should exercise truncation", halfUpDivergences > 0);
    }

    private static List<String> readLines(Path path) throws IOException {
        return Files.readAllLines(path, StandardCharsets.UTF_8);
    }

    private static BigDecimal factor(String line, int start) {
        return new BigDecimal(line.substring(start, start + 7)).movePointLeft(4);
    }

    private static String money(BigDecimal value) {
        return value.setScale(2, RoundingMode.UNNECESSARY).toPlainString();
    }

    /** What a naive port that rounds HALF_UP at each step would produce. */
    private static BigDecimal halfUpFinalPremium(String policyType, RatingFactors f) {
        BigDecimal base = PremiumCalculator.basePremiumFor(policyType);
        BigDecimal p = base.multiply(f.getTerritoryFactor()).setScale(2, RoundingMode.HALF_UP);
        p = p.multiply(f.getClassFactor()).setScale(2, RoundingMode.HALF_UP);
        p = p.multiply(f.getExperienceMod()).setScale(2, RoundingMode.HALF_UP);
        BigDecimal tax = p.multiply(PremiumCalculator.TAX_RATE).setScale(2, RoundingMode.HALF_UP);
        return p.add(tax).add(PremiumCalculator.REGULATORY_SURCHARGE);
    }
}
